# DO NOT EDIT THIS FILE!
#
# Python module CORBAManagerRef__POA generated by omniidl

import omniORB
omniORB.updateModule("CORBAManagerRef__POA")

# ** 1. Stub files contributing to this module
import Manager_idl

# ** 2. Sub-modules

# ** 3. End
