# DO NOT EDIT THIS FILE!
#
# Python module CORBADemo generated by omniidl

import omniORB
omniORB.updateModule("CORBADemo")

# ** 1. Stub files contributing to this module
import Hello_idl

# ** 2. Sub-modules

# ** 3. End
